# 文件名: train_JP1_baseline.yml

name: train_jp1_rrdbnet_laplace  # 实验A的名称
use_tb_logger: true
model: sr 
distortion: sr
scale: 4
gpu_ids: [0] # 请根据您的机器修改GPU编号

datasets:
  train:
    name: JP1_Train
    mode: LQGT
    dataroot_GT: /hdd/SunZL/data/SuperResolutionData/JP1-LAPLACE/train_GT
    dataroot_LQ: /hdd/SunZL/data/SuperResolutionData/JP1-LAPLACE/train_LQ
    use_shuffle: true
    n_workers: 8
    batch_size: 32
    GT_size: 64
    LQ_size: 16
    use_flip: true
    use_rot: true
    color: Gray
    data_type: img


  val:
    name: JP1_Val
    mode: LQGT
    dataroot_GT: /hdd/SunZL/data/SuperResolutionData/JP1-LAPLACE/val_GT
    dataroot_LQ: /hdd/SunZL/data/SuperResolutionData/JP1-LAPLACE/val_LQ
    dataroot_mask: /hdd/SunZL/data/SuperResolutionData/JP1/jp1_ocean_mask.npy

path:
  pretrain_model_G: null
  strict_load: true
  resume_state: null

network_G:
  which_model_G: RRDBNet # 使用RRDBNet作为基线模型
  in_nc: 1
  out_nc: 1
  nf: 64
  nb: 23

train:
  lr_G: !!float 2e-4
  beta1: 0.9
  beta2: 0.999
  warmup_iter: -1
  lr_scheme: MultiStepLR
  lr_steps: [50000, 100000, 200000, 300000]
  lr_gamma: 0.5

  pixel_criterion: 'l1' 
  pixel_weight: 1.0

  manual_seed: 10
  niter: 500000
  val_freq: 5000

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5000