# Not exactly the same as SRResNet in <Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial Network>
# With 16 Residual blocks w/o BN

#### general settings
name: train_jp1_srcnn_laplace
use_tb_logger: false
model: sr
distortion: sr
scale: 4
gpu_ids: [3]

#### datasets
datasets:
  train:
    name: JP1_Train
    mode: LQGT
    dataroot_GT: /hdd/SunZL/data/SuperResolutionData/JP1-LAPLACE/train_GT
    dataroot_LQ: /hdd/SunZL/data/SuperResolutionData/JP1-LAPLACE/train_LQ

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 32
    GT_size: 64
    use_flip: true
    use_rot: true
    color: gray
  val:
    name: JP1_Val
    mode: LQGT
    dataroot_GT: /hdd/SunZL/data/SuperResolutionData/JP1-LAPLACE/val_GT
    dataroot_LQ: /hdd/SunZL/data/SuperResolutionData/JP1-LAPLACE/val_LQ
    dataroot_mask: /hdd/SunZL/data/SuperResolutionData/JP1/jp1_ocean_mask.npy

#### network structures
network_G:
  which_model_G: SRCNN
  in_nc: 1
  out_nc: 1
  nf: 64
  nb: 16
  upscale: 4

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 25000
  warmup_iter: -1  # no warm up
  T_period: [25000, 250000, 250000, 250000]
  restarts: [25000, 500000, 750000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 10
  val_freq: 1578  # !!float 1e2

#### logger
logger:
  print_freq: 1578
  save_checkpoint_freq: 1578
