# 文件名: train_RCAN_baseline.yml

#### general settings
name: train_jp1_rcan_baseline # 实验名：RCAN + 基线(填0)法
use_tb_logger: true
model: sr
distortion: sr
scale: 4
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: JP1_Train_Fillna
    mode: LQGT
    # --- 使用您的填0基线数据 ---
    dataroot_GT: /hdd/SunZL/data/SuperResolutionData/JP1-fillna/train_GT
    dataroot_LQ: /hdd/SunZL/data/SuperResolutionData/JP1-fillna/train_LQ
    # ---------------------------
    use_shuffle: true
    n_workers: 8
    batch_size: 32   # 对齐作者设置
    GT_size: 64
    use_flip: true  # 对齐作者设置
    use_rot: true   # 对齐作者设置
    color: Gray
    data_type: img

  val:
    name: JP1_Val_Fillna
    mode: LQGT
    dataroot_GT: /hdd/SunZL/data/SuperResolutionData/JP1-fillna/val_GT
    dataroot_LQ: /hdd/SunZL/data/SuperResolutionData/JP1-fillna/val_LQ
    # --- 使用相同的精确验证掩码 ---
    dataroot_mask: /hdd/SunZL/data/SuperResolutionData/JP1/jp1_ocean_mask.npy

#### network structures
network_G:
  which_model_G: RCAN # <-- 指定模型为 RCAN
  in_nc: 1
  out_nc: 1
  nf: 64
  nb: 16 # <-- 对齐作者RCAN的网络块数

#### path
path:
  pretrain_model_G: null
  strict_load: true
  resume_state: null

#### training settings: learning rate scheme, loss
train:
  # --- 所有训练超参数均与作者对齐 ---
  lr_G: !!float 2e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 25000
  warmup_iter: -1
  T_period: [25000, 250000, 250000, 250000]
  restarts: [25000, 500000, 750000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7
  pixel_criterion: l1
  pixel_weight: 1.0
  manual_seed: 10
  val_freq: 263

#### logger
logger:
  print_freq: 263
  save_checkpoint_freq: 263