# 文件名: train_JP1_LAPLACE_sansisr_aligned.yml
# (已根据作者的参考配置进行超参数对齐)

name: train_jp1_sansisr_laplace
use_tb_logger: true
model: sr 
distortion: sr
scale: 4
gpu_ids: [0]

datasets:
  train:
    name: JP1_Train
    mode: LQGT
    dataroot_GT: /hdd/SunZL/data/SuperResolutionData/JP1-LAPLACE/train_GT
    dataroot_LQ: /hdd/SunZL/data/SuperResolutionData/JP1-LAPLACE/train_LQ
    use_shuffle: true
    n_workers: 8
    batch_size: 32   # <-- 对齐：从16改为32
    GT_size: 64
    LQ_size: 16
    use_flip: true
    use_rot: true
    color: Gray
    data_type: img

  val:
    name: JP1_Val
    mode: LQGT
    dataroot_GT: /hdd/SunZL/data/SuperResolutionData/JP1-LAPLACE/val_GT
    dataroot_LQ: /hdd/SunZL/data/SuperResolutionData/JP1-LAPLACE/val_LQ
    dataroot_mask: /hdd/SunZL/data/SuperResolutionData/JP1/jp1_ocean_mask.npy

path:
  pretrain_model_G: null
  strict_load: true
  resume_state: null

network_G:
  which_model_G: SANSISR
  in_nc: 1
  out_nc: 1
  nf: 64
  nb: 16 # <-- 对齐：SANSISR的块数量从23改为16

train:
  lr_G: !!float 1e-4 # <-- 对齐：学习率改为 1e-4
  beta1: 0.9
  beta2: 0.99 # <-- 对齐：beta2 改为 0.99
  warmup_iter: -1
  
  # --- 关键改动：学习率方案与作者完全对齐 ---
  lr_scheme: CosineAnnealingLR_Restart
  T_period: [25000, 250000, 250000, 250000]
  restarts: [25000, 500000, 750000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7
  # -----------------------------------------

  pixel_criterion: 'l1' 
  pixel_weight: 1.0

  manual_seed: 10
  niter: 25000 # <-- 对齐：总迭代次数改为25000
  val_freq: 263 # <-- 对齐：验证频率

logger:
  print_freq: 263 # <-- 对齐：日志打印频率
  save_checkpoint_freq: !!float 263 # <-- 对齐：模型保存频率